# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pzQN9PSBPQybYPmOyNwljoXYQ568AY+oVF9nQj2re9q9L1Hi65ZITw==,iv:7wwLNNDEgr2E76KLg32msKGciqvGzUeZcOglSP1Cxg4=,tag:V8FZMBedk3R0dvb0EeD1wA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123tswk3a0dz0zy453vqhhuu6n4xn0h3s7x380xfaafr3v6zx2adqkvwkaf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMWxqYko3YncrNzBuaTNm
        S2hlM1N0c1M2VWZvc1h3OVhtcWJWb1hmUnkwCmJINTkwL0RnRnhTODNBQTNtbFFs
        bHEvbnpZZTJTc3dzaGp4SGVYR3dyblkKLS0tIGRuSDNzaTI1V0twZTBsaTF5ei9R
        NTZNK0ZORWdFVk1hK3Y5WEpVZnlnZ3cKispoQyYhFbKuVaNW9hYmP2e4CCZGsYcs
        ZNo1BSk1X5b+PSB89YRB+8ekYlZOEw5+TmXh0xvZYlGk7xv0ng814Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T05:03:05Z"
  mac: ENC[AES256_GCM,data:fhs5Zb0Cq+Egzq3eK7eVOZQegTBiLZwJUJFNWIo93O0B8hhkRpNydDmYOUuFMaV3bvZrV42y4T0Ebncuu2qxs2lTDFnBRTBpJX7qgW9WVkEVpkEUFoTEPKHtFafGz6DZihLW9PE7P21pvn7ODiKxbUMPmO6/rinLWqDw3eV/S1o=,iv:Ahxs4vsmOaistA+nVMJoxrPUpqmJfXzwVgJWFYfiWdQ=,tag:Cd4QU8ZEHiIoxeL3MGC2XQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
