# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lLBrbUOTnVUPvjo5E7e5M9Nolh0gqUG0OLyAbZI1aeg=,iv:KIZR2cDT5jwPipxiH2NHWAdDvF5ZUSelmLVdQFUarz0=,tag:jQp6n7MAESMbZx+4aqbWwQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123tswk3a0dz0zy453vqhhuu6n4xn0h3s7x380xfaafr3v6zx2adqkvwkaf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL09rSVA2bEJ4Q2M3YWxi
        dFZnemMzK0lwQWlOd0huWjhnTExid3puZ3k0Ckd0aDB3dkJTaTBvZnRmcDVNMzd4
        OG5hQUMxTHNHUWdaSjhHMFF5SHRMeTAKLS0tIDQvelIzVmlBT1BZcnBML0ZIekk5
        YjB2T2hKdVd2U2pZOFVoSWJ2dzJtMkkKRDBJQ8iJUy4pggT/zf9SrQJfXfQVskHr
        fIAgNr48qnB2ua9utzkL2+MHDY/gUT6V3ogCjK5Gu4Lc2VWsj37FIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-02T04:30:25Z"
  mac: ENC[AES256_GCM,data:fadF/if3q8Vo7loa5j66DMpEhP/f1IwcJtqnf/lqXwXJs2yE0ITKdXRcuC0C+180f0Sk424XLb3iuUc1vmkofC1zjV/zxkdu8PH+CxyFOz9B8WiuYmREQp7uSKfnwPjCK4Fw6zZAitorYZi4AbIqoG9aLDmjaZyTZiifPD+08JA=,iv:OLLYNI0Vywq55iz+cizw8IgAKh4/H/SXMeIt74y6BIo=,tag:MvNjlsfR9ZDiVb77I0zByg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
